// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PrettierX64
{
    static class Vsix
    {
		public const string Id = "d917daa5-aba6-4384-b082-9ccf9e8472f4";
		public const string Name = "Prettier x64";
		public const string Description = @"Prettier is an opinionated code formatter. It enforces a consistent style by parsing your code and re-printing it with its own rules that take the maximum line length into account, wrapping code when necessary.";
		public const string Language = "en-US";
		public const string Version = "1.0";
		public const string Author = "vs-publisher-126251";
		public const string Tags = "JavaScript;JSX;EcmaScript;TypeScript;formatting";
    }
}
