// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PrettierX64
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPrettierPackageString = "ef0c71c2-4568-443f-a0e5-e8490aeff5eb";
        public const string guidPrettierPackageCmdSetString = "3afdacda-dc22-4a63-9c5f-e9c0520276e1";
        public static Guid guidPrettierPackage = new Guid(guidPrettierPackageString);
        public static Guid guidPrettierPackageCmdSet = new Guid(guidPrettierPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PrettierCommandId = 0x0100;
    }
}
